extends:
  - "spectral:oas"
rules:
  # ---------------------------------------------------------------------------
  # Schema rules
  # ---------------------------------------------------------------------------
  info-version-semver:
    severity: error
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version.
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+.[0-9]+.[0-9]+)$"

  # ---------------------------------------------------------------------------
  # API Rules
  # ---------------------------------------------------------------------------

  server-url-must-contain-version:
    description: Global API version must be present in the path
    severity: error
    recommended: true
    message: "Unversioned server URL detected: {{value}}"
    given: "$.servers[*].url"
    then:
      function: pattern
      functionOptions:
        match: "\/v[1-9]+\/"
